version: '3'

services:
  api:
    build: ./
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      MYSQL_DB_PASSWORD: strong_password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
  
  db:
    image: mysql:oraclelinux9
    ports:
      - 3307:3306 # just for debugging, the other containers can only see 3306
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
    volumes:
      - pokdb:/data/db

volumes:
  pokdb: